v3.0.0

diff --git a/mailpixtracker b/mailpixtracker
--- a/mailpixtracker
+++ b/mailpixtracker
@@ -3,7 +3,7 @@
 export VERSION=3.0.0
 export PROGNAME='Mail Pix Tracker'
 export source='https://github.com/ColasNahaboo/mailpixtracker'
-export copyright='(c)2026 Colas Nahaboo, MIT License'
+export copyright='(c)2026 Colas Nahaboo, GPL V3 License'
 
 # globals. Can be redefined in the sourced file ../mailpixtracker.conf
 configfile='../mailpixtracker.conf'
@@ -544,7 +544,17 @@ logo='iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IB2cksfwAAAARnQU1BAA
 htmail_logo='iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAMAAADzapwJAAAAAXNSR0IB2cksfwAAAARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAAOpgAABdwnLpRPAAAAgFQTFRFAAAAAAAAREdGREdGREdGREdGREdGRklIRUhHREdGRklIU1ZVS05NWVxbS05NRklIVFdWXmFgRklISUxLc3V0XV9eW11dTlFQRUhHTlFQXV9fWFtaUFNSR0pJSUxLS05NRklIV1lZS05NRklITE9OoqOiZ2loTE9ORklIRUhHTE9OV1pZRklITE5OTVBPR0pJSUxLWFpaSEtKSEtKVVhXTU9ORUhHUVRTZWdmTE9OREdGRklIT1JRUFJRRklIRUhHTE9OXmFgdHd2SEtKR0pJd3p5U1VUS05Nd3p5SEtKTE9Ob3FwRUhHTlFQUVRTRklIRklIW15dU1VVSEtKSEtKT1JRSk1MRklIVVhXV1pZSk1MRklITE9OXmFgSUxLRUhHRklIS05Nam1sWFtaR0pJSEtKUFJRSEtKRUhHSEtKUlVUTlFQR0pJTVBPRUhHTU9OTU9PRUhHRkhHS05NaGtqWFtaS05NSUxLSEtKR0lIZmdnTE9OR0pJVFdW0NHRiIqJcHNySk1M6OjoYmVkUFNSRklITE9OUlVUWVxbSUxLR0pJR0pJSEtKhIaFUlVUSUxLRklITE5OTU9OTlBPSEtKRUhHY2VkTE9OSEtKSk1MVVhXVFZVSk1MTE5NUlVUSUxLTVBPZGZlTU9OR0pJYWRjeXp5UFNSSUxLRUhHSEtKTE9OQSeK0AAAAAF0Uk5TAEDm2GYAAAABYktHRACIBR1IAAAACXBIWXMAABYlAAAWJQFJUiTwAAAAB3RJTUUH6QsZBDAYbH3PlwAAAGpJREFUGNOtkTESgEAIAzNpQm/NJ+53/l4d9eDktJJyJwlMADgZgCrQRNBQZpcfjm/sc6wndl1iecJKGeq4eVrnHiEaxLFyAdYIernbArebNWNVy86uhk56bUevltwJk+ruAdc//ILnL94Az6AE8m6Sfn0AAAAASUVORK5CYII='
 
 editicon='iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAAAXNSR0IB2cksfwAAAARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAAOpgAABdwnLpRPAAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB+oDBxMhHVCFtD4AAAG8SURBVDjLpdS7axRBHAfwz+wFCy3TCD5u8bBQBFGxFnwgMYKNEtMoiDEWiqW2IopgqQgSX2gkphFRixTiqzZWooWc7BkEi/wDGm7HZg7XkOQuZGCaHeYz3/nNzAYrbI16fgCPEXAyrBAbwLPUV2P3f2C+Lg+CRReJUWz9LGLCDuI5SmzDDezoS4MncBXru4T6iq0VbAI78SXBA6FRz4dxG2fxGr+XAP9gD15gPLbjaKiFcRzBoWareN+Hi7jQbBWTPdRs/zzsQRWDDNtT5G7YPrzEeFnqYEerWAfs5TT3JuxJjHE0y9xP2GAV6wlM2CtMtMv2mRDCPRzDYFmWHxr1/OOmDRtDT+A8bKSW1e5iKCV7F2OsYVcIMesKVrGybaSW1cZwvIMtNi/rgj0tYxzJasYwjMPNVvF2qV1lC2D96WpMivF0FkIVe9Ot5gslPIc5XLJMDPrmpVuD85jF5/Tge8YWSngK/ViLR8iXg3USxtThGy7jVrNVzHZNk2Wr0l+orILT6flNN1vFFKZ6TRNC2I9f32dmYhW8joeNej6HT5W03doW3Ew7+rdIOowhXMHmZZTrB641W8Wd6se/E8WtW4e9Pz0AAAAASUVORK5CYII='
-        
+
+################################# Check requirements
+rawerr(){ echo $'Content-Type: text/plain\n\nError: '"$*"; exit 1;}
+# Check Bash version
+if ((BASH_VERSINFO[0] < 4)) || [[ ${BASH_VERSINFO[0]} -eq 4 && ${BASH_VERSINFO[1]} -lt 2 ]]; then rawerr "Bash 4.2+ required, but we are on $BASH_VERSION"
+fi
+# Fallback for 'tac' (using sed)
+command -v tac >/dev/null 2>&1 || tac() { sed '1!G;h;$!d' "$@"; }
+# realpath
+command -v realpath >/dev/null 2>&1 || rawerr 'realpath not found!'
+
 ################################# Main logic dispatcher
 
 # shellcheck disable=SC1091 # Ok to not check included file syntax
